version: 2
jobs:
  build:
    docker:
      - image: mikeastock/rust:nightly-2017-11-20
        environment:
          - DATABASE_URL=postgres://postgres@localhost/mob_test
      - image: circleci/postgres:9.6
        environment:
          - POSTGRES_DB=mob_test
    working_directory: /mob
    steps:
      - checkout
      - restore_cache:
          key: mob-v1-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Setup Database
          command: cd server && diesel setup
      - run:
          name: Build
          command: cargo build --all
      - run:
          name: Run Tests
          command: RUST_TEST_THREADS=1 cargo test --all
      - save_cache:
          key: mob-v1-{{ checksum "Cargo.lock" }}
          paths:
            - ~/.cargo
