version: 2
jobs:
  build:
    docker:
      - image: mikeastock/rust:0.2
    working_directory: ~/mob
    steps:
      - checkout
      - run:
          name: Build
          command: cargo build --all
      - run:
          name: Run Tests
          command: RUST_TEST_THREADS=1 cargo test --all
