version: 2
jobs:
  build:
    docker:
      - image: mikeastock/rust:0.3
        environment:
          - PGHOST=localhost
          - PGUSER=ubuntu
          - DATABASE_URL=postgres:///mob_test
      - image: postgres:9.6
        environment:
          - POSTGRES_USER=ubuntu
          - POSTGRES_DB=mob_test
    working_directory: ~/mob
    steps:
      - checkout
      - run:
          name: Build
          command: cargo build
      - run:
          name: Run Tests
          command: RUST_TEST_THREADS=1 cargo test
